var data = [
	{"name": "Como en Casa", "type": "Mexicana", "price": "$$", "image": "../assets/images/gorditas.jpg", "adress": "Apartado núm.: 951, 1992 Lacinia Avenida", "zone": "Poniente", "description": "Práctico, rico y directo a tu mesa"},
	{"name": "La Dolce Vita", "type": "Italiana", "price": "$$$", "image": "../assets/images/tiramisu.jpeg", "adress": "388-1898 Auctor Avenida", "zone": "Sur", "description": "Auténtica comida italiana"},
	{"name": "Angel Maid", "type": "Japonesa", "price": "$", "image": "../assets/images/food2.jpg", "adress": "816-7814 Id, Ctra.", "zone": "Oriente", "description": ""},
	{"name": "Vel Vulputate", "type": "Italiana", "price": "$", "image": "../assets/images/lasagna.jpg", "adress": "1831 Sed Carretera", "zone": "Norte", "description": "De la Toscana a tu domicilio"},
	{"name": "La Nuit", "type": "Francesa", "price": "$$$", "image": "../assets/images/crepe.jpg", "adress": "Apdo.:904-2774 Dis C/", "zone": "Sur", "description": "Las crepas más dulces"},
	{"name": "Moshi", "type": "Japonesa", "price": "$", "image": "../assets/images/ramen.jpg", "adress": "Apartado núm.: 108, 8742 Eu Carretera", "zone": "Norte", "description": "", "description": "El mejor ramen al norte"},
	{"name": "Auctor Non", "type": " Japonesa ", "price": "$", "image": "../assets/images/sushi.jpg", "adress": "1376 Lectus C.", "zone": "Norte", "description": "Sushi Express"},
	{"name": "Flor Azteca", "type": "Mexicana", "price": "$$$", "image": "../assets/images/taquitos.jpg", "adress": "402-9200 Leo. Carretera", "zone": "Centro", "description": "Tacos perrones"},
	{"name": "Ipsum Primis", "type": "Italiana", "price": "$$", "image": "../assets/images/pasta.jpg", "adress": "Apartado núm.: 235, 8102 Ridiculus Carretera", "zone": "Poniente", "description": "Con la bolognesa de la casa"},
	{"name": "Taco Taco", "type": "Mexicana", "price": "$", "image": "../assets/images/pozole.jpg", "adress": "Apartado núm.: 560, 1720 A ", "zone": "Poniente", "description": "Antojo a la puerta de tu casa"},
	{"name": "Seine", "type": "Francesa", "price": "$$", "image": "../assets/images/macarons.jpg", "adress": "473-5525 Ligula. C.", "zone": "Oriente", "description": "Llevamos dulzura a tu vida"},
	{"name": "Yue", "type": "Japonesa", "price": "$$", "image": "../assets/images/bento.jpg", "adress": "347-9001 Odio Ctra.", "zone": "Sur", "description": "Rápido y delicioso"},
	{"name": "Chat Noir", "type": "Francesa", "price": "$$$", "image": "../assets/images/french.cheese.jpg", "adress": "Apdo.:201-213 Aliquam Av.", "zone": "Sur", "description": "Pan frances artesanal"},
	{"name": "Bon Appétit", "type": "Francesa", "price": "$$", "image": "../assets/images/ratatouille.jpg", "adress": "Apartado núm.: 884, 4122 Velit Calle", "zone": "Norte", "description": "Tradicional comida francesa"},
	{"name": "Sakura", "type": "Japonesa", "price": "$$$", "image": "../assets/images/food.jpg", "adress": "Apartado núm.: 830, 4732 Primis Avenida", "zone": "Oriente", "description": "Comida japonesa a tu hogar"},
	{"name": "Sparta", "type": "Italiana", "price": "$$", "image": "../assets/images/pizza.jpeg", "adress": "3654 Fringilla, Avda.", "zone": "Poniente", "description": "Pizza artesanal"},
	{"name": "Doña Pelos", "type": "Mexicana", "price": "$", "image": "../assets/images/quecas.jpg", "adress": "4579 Et C.", "zone": "Centro", "description": "El auténtico sabor de Doña Pelos"},
	{"name": "Je ne sais pas", "type": "Francesa", "price": "$", "image": "../assets/images/meat.jpg", "adress": "560-5124 Nonummy. C/", "zone": "Centro", "description": "Gourmet a tu domicilio"},
];
